### ISSUE TITLE
Design improvements 

### ISSUE THREAD

**Issue by JoeDalton9027** [AzuriomCommunity/Theme-Guide#2]
Add a way to display trailers on the homepage
Add some spaces between usefull links buttons. (https://prnt.sc/GzqfsvMaT0UV)
Add some space between singup and singin button (https://prnt.sc/_F0ADUut3sS-)

Advantages
Allow users to promote one videos for the server, for exemple, this could be add under the discord ID

Improve the visual appearance of the theme.

**Comment by MrMicky-FR** [comment]
Added in 0906ef72055bd3f0a3794567e275ca89d5b78e8d, release will be published soon
